using System.Text;
using System.Collections.Immutable;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MemoryLayout.Generator
{
    [Generator]
    public class MemoryLayoutGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is StructDeclarationSyntax { AttributeLists.Count: > 0 },
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            IncrementalValueProvider<(Compilation, ImmutableArray<StructDeclarationSyntax?>)> compilationAndStructs
                = context.CompilationProvider.Combine(structDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndStructs,
                static (spc, source) => Execute(source.Item1, source.Item2!, spc));
        }

        private static StructDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var structDeclaration = (StructDeclarationSyntax)context.Node;
            foreach (var attributeList in structDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attributeSymbol &&
                        attributeSymbol.ContainingType.ToDisplayString() == "MemoryLayout.Abstractions.MemoryLayoutContractAttribute")
                    {
                        return structDeclaration;
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<StructDeclarationSyntax> structs, SourceProductionContext context)
        {
            if (structs.IsDefaultOrEmpty) return;

            foreach (var structDef in structs.Distinct())
            {
                var model = compilation.GetSemanticModel(structDef.SyntaxTree);
                if (model.GetDeclaredSymbol(structDef) is not INamedTypeSymbol structSymbol) continue;

                string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
                string structName = structSymbol.Name;

                string source = GenerateLayoutCode(namespaceName, structName);
                context.AddSource($"{structName}_LayoutEncoder.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GenerateLayoutCode(string namespaceName, string structName)
        {
            ushort typeId = GenerateDeterministicId(structName);

            return $@"// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using MemoryLayout;

namespace {namespaceName}
{{
    // Forzamos el layout secuencial para asegurar que CopyBlock sea idéntico en ambos lados
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe partial struct {structName} : global::MemoryLayout.Abstractions.IMemoryLayout<{structName}>
    {{
        /// <summary>
        /// ID único generado automáticamente mediante Hash determinista del nombre del tipo.
        /// </summary>
        public static ushort TypeId => {typeId};

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Encode(ref byte dest, out int totalBytes)
        {{
            totalBytes = sizeof({structName});
            
            // HFC: Copia directa de memoria sin mapeos ni bucles
            Unsafe.WriteUnaligned(ref dest, this);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void Decode(ReadOnlySpan<byte> buffer, out {structName} result)
        {{
            if (buffer.Length < sizeof({structName}))
                throw new ArgumentException(""Buffer too small"");

            // HFC: Lectura directa de memoria al struct
            result = Unsafe.ReadUnaligned<{structName}>(ref MemoryMarshal.GetReference(buffer));
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int GetByteSize() => sizeof({structName});
    }}
}}";
        }

        /// <summary>
        /// Genera un ID de 16 bits determinista basado en el nombre del struct.
        /// </summary>
        private static ushort GenerateDeterministicId(string structName)
        {
            uint hash = 2166136261;
            foreach (char c in structName)
            {
                hash = (hash ^ (uint)c) * 16777619;
            }
            // Reducción plegada para minimizar colisiones en 16 bits
            return (ushort)((hash >> 16) ^ (hash & 0xFFFF));
        }
    }
}