using System.Text;
using System.Collections.Immutable;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MemoryLayout.Generator
{
    [Generator]
    public class MemoryLayoutGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is StructDeclarationSyntax { AttributeLists.Count: > 0 },
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            IncrementalValueProvider<(Compilation, ImmutableArray<StructDeclarationSyntax?>)> compilationAndStructs
                = context.CompilationProvider.Combine(structDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndStructs,
                static (spc, source) => Execute(source.Item1, source.Item2!, spc));
        }

        private static StructDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var structDeclaration = (StructDeclarationSyntax)context.Node;
            foreach (var attributeList in structDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attributeSymbol &&
                        attributeSymbol.ContainingType.ToDisplayString() == "MemoryLayout.Abstractions.MemoryLayoutContractAttribute")
                    {
                        return structDeclaration;
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<StructDeclarationSyntax> structs, SourceProductionContext context)
        {
            if (structs.IsDefaultOrEmpty) return;

            foreach (var structDef in structs.Distinct())
            {
                var model = compilation.GetSemanticModel(structDef.SyntaxTree);
                if (model.GetDeclaredSymbol(structDef) is not INamedTypeSymbol structSymbol) continue;

                string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
                string structName = structSymbol.Name;

                string source = GenerateLayoutCode(namespaceName, structName, structSymbol);
                context.AddSource($"{structName}_LayoutEncoder.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GenerateLayoutCode(string ns, string name, INamedTypeSymbol symbol)
        {
            var fields = symbol.GetMembers().OfType<IFieldSymbol>().ToList();
            var extensionMethods = new StringBuilder();
            var internalFields = new StringBuilder();

            foreach (var f in fields)
            {
                var bufferAttr = f.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "MemoryBufferAttribute");

                if (bufferAttr != null && f.Type.SpecialType == SpecialType.System_String)
                {
                    int size = (int)bufferAttr.ConstructorArguments[0].Value!;

                    // 1. Generar campos internos fixed para el struct
                    internalFields.AppendLine($"        internal fixed byte _{f.Name}_buffer[{size}];");
                    internalFields.AppendLine($"        internal int _{f.Name}_len;");

                    // 2. Generar métodos de extensión para la "Elegancia"
                    extensionMethods.AppendLine($@"
                    public static string Get{f.Name}(this ref {name} msg)
                    {{
                        if (msg._{f.Name}_len <= 0) return string.Empty;
                        unsafe {{
                            fixed (byte* p = msg._{f.Name}_buffer)
                                return global::System.Text.Encoding.UTF8.GetString(p, msg._{f.Name}_len);
                        }}
                    }}

                    public static void Set{f.Name}(this ref {name} msg, string value)
                    {{
                        if (string.IsNullOrEmpty(value)) {{ msg._{f.Name}_len = 0; return; }}
                        var bytes = global::System.Text.Encoding.UTF8.GetBytes(value);
                        msg._{f.Name}_len = Math.Min(bytes.Length, {size});
                        unsafe {{
                            fixed (byte* p = msg._{f.Name}_buffer)
                                global::System.Runtime.InteropServices.Marshal.Copy(bytes, 0, (IntPtr)p, msg._{f.Name}_len);
                        }}
                    }}");
                }
            }

            return $@"
            // <auto-generated/>
            using System;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;

            namespace {ns}
            {{
                [StructLayout(LayoutKind.Sequential, Pack = 1)]
                public unsafe partial struct {name} : global::MemoryLayout.Abstractions.IMemoryLayout<{name}>
                {{
                    {internalFields}

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    public void Encode(ref byte dest, out int totalBytes)
                    {{
                        uint size = (uint)Unsafe.SizeOf<{name}>();
                        Unsafe.CopyBlockUnaligned(ref dest, ref Unsafe.As<{name}, byte>(ref this), size);
                        totalBytes = (int)size;
                    }}

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    public static {name} Decode(ref byte source, int length)
                    {{
                        return Unsafe.ReadUnaligned<{name}>(ref source);
                    }}
                }}

                public static class {name}Extensions
                {{
                    {extensionMethods}
                }}
            }}";
        }
    }
}